# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: gp3
# provisioner: kubernetes.io/aws-ebs
# parameters:
#   type: gp3
#   fsType: ext4
#   # iopsPerGB: "50" # Optional: Adjust IOPS per GB
#   # encrypted: "true" # Optional: Enable encryption
#   # kmsKeyId: "your-kms-key-id" # Optional: Specify KMS key for encryption
# reclaimPolicy: Retain
# volumeBindingMode: WaitForFirstConsumer